# Generated by Django 2.2 on 2019-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(default='CREATING', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_table',
                'ordering': ['create_time'],
            },
        ),
    ]
